"""CellRank lineage analysis.

Purpose:
    Representative analysis code for reconstructing the otic progenitor -> early
    hair cell -> late hair cell trajectory using CellRank. This script uses the
    RNA velocity object generated by rna_velocity_analysis.py.
"""

from pathlib import Path

import cellrank as cr
import matplotlib.pyplot as plt
import scanpy as sc
import scvelo as scv

scv.settings.verbosity = 3
cr.settings.verbosity = 2

PROJECT_DIR = Path(".")
ANNDATA_DIR = PROJECT_DIR / "anndata"
FIG_DIR = PROJECT_DIR / "figures"
RESULT_DIR = PROJECT_DIR / "processed_data"
FIG_DIR.mkdir(parents=True, exist_ok=True)
RESULT_DIR.mkdir(parents=True, exist_ok=True)

INPUT_H5AD = ANNDATA_DIR / "integrated_anndata_velocity_lineage_subset.h5ad"
OUTPUT_H5AD = ANNDATA_DIR / "cellrank_lineage_results.h5ad"

adata = sc.read_h5ad(INPUT_H5AD)

# ---------------------------------------------------------------------
# Build velocity/connectivity kernels
# ---------------------------------------------------------------------

vk = cr.kernels.VelocityKernel(adata)
vk.compute_transition_matrix()

ck = cr.kernels.ConnectivityKernel(adata)
ck.compute_transition_matrix()

combined_kernel = 0.8 * vk + 0.2 * ck
combined_kernel.write_to_adata()

vk.plot_projection(
    color="cell_type" if "cell_type" in adata.obs else "wsnn_clusters",
    arrow_size=1,
    density=2,
    smooth=0.9,
    save=str(FIG_DIR / "cellrank_velocity_projection.png"),
    dpi=300,
)

# ---------------------------------------------------------------------
# GPCCA estimator and macrostates
# ---------------------------------------------------------------------

g = cr.estimators.GPCCA(combined_kernel)

# Macrostates may be set manually based on known cluster/cell-type labels.
# The labels below reflect the lineage analysis in the manuscript. Adjust them
# if local CellRank macrostate names differ.
try:
    g.set_terminal_states(states=["EHC", "LHC_2", "Otic_5"])
    g.set_initial_states(states=["Otic_1"])
except Exception:
    # Alternative: estimate macrostates automatically, then inspect and adjust.
    g.compute_schur(n_components=4)
    g.compute_macrostates(n_states=4, cluster_key="cell_type" if "cell_type" in adata.obs else None)

# Plot initial and terminal macrostates.
g.plot_macrostates(which="all", s=100, legend_loc="center")
plt.savefig(FIG_DIR / "cellrank_all_macrostates.pdf", bbox_inches="tight")
plt.close()

g.plot_macrostates(which="terminal", s=100, legend_loc="center")
plt.savefig(FIG_DIR / "cellrank_terminal_states.pdf", bbox_inches="tight")
plt.close()

g.plot_macrostates(which="initial", s=100, legend_loc="right")
plt.savefig(FIG_DIR / "cellrank_initial_states.pdf", bbox_inches="tight")
plt.close()

# ---------------------------------------------------------------------
# Fate probabilities and driver genes
# ---------------------------------------------------------------------

g.compute_fate_probabilities()
g.plot_fate_probabilities(same_plot=False)
plt.savefig(FIG_DIR / "cellrank_fate_probabilities.pdf", bbox_inches="tight")
plt.close()

# Driver genes for early and late hair-cell lineages.
for lineage in ["EHC", "LHC_2"]:
    try:
        drivers = g.compute_lineage_drivers(lineages=[lineage], return_drivers=True)
        drivers.to_csv(RESULT_DIR / f"cellrank_{lineage}_driver_genes.csv")
    except Exception as exc:
        print(f"Skipping lineage {lineage}: {exc}")

# Heatmap of EHC driver genes over pseudotime.
try:
    model = cr.models.GAM(adata, n_knots=6)
    ehc_drivers = g.compute_lineage_drivers(lineages="EHC")
    cr.pl.heatmap(
        adata,
        model=model,
        lineages=["EHC"],
        genes=ehc_drivers.head(100).index,
        cluster_key="cell_type",
        show_fate_probabilities=True,
        time_key="velocity_pseudotime" if "velocity_pseudotime" in adata.obs else "pseudotime",
        figsize=(12, 10),
        show_all_genes=False,
        weight_threshold=(1e-3, 1e-3),
        save=str(FIG_DIR / "cellrank_EHC_driver_heatmap.png"),
    )
except Exception as exc:
    print(f"Driver heatmap was not generated: {exc}")

adata.write(OUTPUT_H5AD, compression="gzip")
